-- MySQL Script generated by MySQL Workbench
-- Tue Jul 29 04:52:44 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema foroUNET
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `foroUNET` ;
CREATE SCHEMA IF NOT EXISTS `foroUNET` DEFAULT CHARACTER SET utf8 ;
USE `foroUNET` ;

-- -----------------------------------------------------
-- Table `foroUNET`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `foroUNET`.`User` ;

CREATE TABLE IF NOT EXISTS `foroUNET`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `rol` ENUM('Administrator','User') NULL DEFAULT 'User',
  `state` ENUM('Active','Inactive','Bloqued') NULL DEFAULT 'Active',
  `online` BOOL NULL,
  `lastConnection` TIMESTAMP NULL,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroUNET`.`Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `foroUNET`.`Type` ;

CREATE TABLE IF NOT EXISTS `foroUNET`.`Type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroUNET`.`Subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `foroUNET`.`Subject` ;

CREATE TABLE IF NOT EXISTS `foroUNET`.`Subject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Type_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  `detail` VARCHAR(1024) NOT NULL,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_Subject_User1_idx` (`User_id` ASC),
  INDEX `fk_Subject_Type1_idx` (`Type_id` ASC),
  CONSTRAINT `fk_Subject_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `foroUNET`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subject_Type1`
    FOREIGN KEY (`Type_id`)
    REFERENCES `foroUNET`.`Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroUNET`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `foroUNET`.`Comment` ;

CREATE TABLE IF NOT EXISTS `foroUNET`.`Comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Subject_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  `detail` VARCHAR(1024) NOT NULL,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_Comment_User1_idx` (`User_id` ASC),
  INDEX `fk_Comment_Subject1_idx` (`Subject_id` ASC),
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `foroUNET`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Subject1`
    FOREIGN KEY (`Subject_id`)
    REFERENCES `foroUNET`.`Subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroUNET`.`Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `foroUNET`.`Message` ;

CREATE TABLE IF NOT EXISTS `foroUNET`.`Message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sender` INT NOT NULL,
  `receiver` INT NOT NULL,
  `message` VARCHAR(1024) NOT NULL,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_Message_User_idx` (`sender` ASC),
  INDEX `fk_Message_User1_idx` (`receiver` ASC),
  CONSTRAINT `fk_Message_User`
    FOREIGN KEY (`sender`)
    REFERENCES `foroUNET`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_User1`
    FOREIGN KEY (`receiver`)
    REFERENCES `foroUNET`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroUNET`.`Publications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `foroUNET`.`Publications` ;

CREATE TABLE IF NOT EXISTS `foroUNET`.`Publications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `User_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `detail` LONGTEXT NOT NULL,
  `type` ENUM('News','Announcements') NOT NULL,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_Publications_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Publications_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `foroUNET`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroUNET`.`Repository`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `foroUNET`.`Repository` ;

CREATE TABLE IF NOT EXISTS `foroUNET`.`Repository` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `User_id` INT NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `data` BLOB NOT NULL,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_Repository_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Repository_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `foroUNET`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO foroUNET;
 DROP USER foroUNET;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'foroUNET' IDENTIFIED BY 'funet';

GRANT ALL ON `foroUNET`.* TO 'foroUNET';
GRANT SELECT ON TABLE `foroUNET`.* TO 'foroUNET';
GRANT SELECT, INSERT, TRIGGER ON TABLE `foroUNET`.* TO 'foroUNET';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `foroUNET`.* TO 'foroUNET';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;